<?php

function get_names() {

return array(
  'Aaron', 'Abdul', 'Abe', 'Abel', 'Abraham', 'Abram', 'Adalberto', 'Adam',
  'Adan', 'Adolfo', 'Adolph', 'Adrian', 'Agustin', 'Ahmad', 'Ahmed', 'Al',
  'Alan', 'Albert', 'Alberto', 'Alden', 'Aldo', 'Alec', 'Alejandro', 'Alex',
  'Alexander', 'Alexis', 'Alfonso', 'Alfonzo', 'Alfred', 'Alfredo', 'Ali',
  'Allan', 'Allen', 'Alonso', 'Alonzo', 'Alphonse', 'Alphonso', 'Alton',
  'Alva', 'Alvaro');
}
