<html>
<head>
<META HTTP-EQUIV="Expires" CONTENT="-1">
<LINK href="site/common.css" rel="stylesheet" type="text/css">
<title>Twister</title></head>
<body>
<div id="centeredmenu">
   <ul>
      <li><a href="index.php">Twists</a></li>
      <li><a href="index.php?type=add">Add a Twist</a></li>
      <li><a href="user.php">Users</a></li>
      <li><a href="register.php">Register</a></li>
      <li><a href="login.php">Login</a></li>
      <li><a href="login.php?type=logout">Logout</a></li>
      <li><a href="index.php?type=xml">XML</a></li>
   </ul>
</div>
<div id="wrapper">
<div id="content">
<div id="item">