<html>
<head>
<META HTTP-EQUIV="Expires" CONTENT="-1">
<LINK href="site/common.css" rel="stylesheet" type="text/css">
<!-- LINK href="site/more.css" rel="stylesheet" type="text/css" -->
<title>Twister</title></head>
<body>
<nav id="centeredmenu">
   <ul>
      <li><a href="index.php">Twists</a></li>
      <li><a href="index.php?action=add">Add a Twist</a></li>
      <li><a href="user.php">Users</a></li>
      <li><a href="register.php">Register</a></li>
      <li><a href="login.php">Login</a></li>
      <li><a href="login.php?action=logout">Logout</a></li>
      <li><a href="index.php?action=xml">XML</a></li>
   </ul>
</nav>
<div id="wrapper">
<div id="content">
<div id="item">