<!-- HTML snippet for login form. -->
<form name="input" action="login.php" method="post">
<fieldset><legend>Login:</legend>
<input type="hidden" name="type" value="login" /><br>
<label for="user_name">Username</label>
<input type="text" name="user_name" value="" /><br>
<label for="password">Password</label>
<input type="password" name="password" value="" /><br>
<input type="submit" value="Log In" />
</fieldset>
</form>
